name = "SimpleCompression"
uuid = "c2c0d5cb-a6e5-4bd7-a12e-febeca281e0f"
authors = ["Ted Dunning <ted.dunning@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
